# -*- coding: utf-8 -*-
"""Summary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-ltSUuiNr3uhXNsEv8z9eObyhdFkDXC
"""

import pandas as pd

!pip install transformers

!pip install sumy
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lsa import LsaSummarizer
from sumy.nlp.stemmers import Stemmer
from sumy.utils import get_stop_words

after_sentiment_data = pd.read_csv('/content/processed_newsgroups_dataset_after_sentiment.csv')
before_sentiment_data = pd.read_csv('/content/processed_newsgroups_dataset_before_sentiment.csv')

# Choose a language
LANGUAGE = "english"

# Get a sample text from the 'before_sentiment_data' DataFrame
sample_text = before_sentiment_data['summary'].iloc[0]

# Initialize parser and tokenizer
parser = PlaintextParser.from_string(sample_text, Tokenizer(LANGUAGE))

# Initialize stemmer and summarizer
stemmer = Stemmer(LANGUAGE)
synthesizer = LsaSummarizer(stemmer)
synthesizer.stop_words = get_stop_words(LANGUAGE)

# Generate a summary with 3 sentences
summary_sentences = synthesizer(parser.document, sentences_count=3)

print("Original Text:\n", sample_text)
print("\nExtractive Summary (LSA):\n")
for sentence in summary_sentences:
    print(sentence)

import pandas as pd

def extract_lsa_summary(text, sentences_count=3, language="english"):
    """
    Generates an extractive summary of the given text using the LSA algorithm.

    Args:
        text (str): The input text to summarize.
        sentences_count (int): The desired number of sentences in the summary.
        language (str): The language of the text (e.g., "english").

    Returns:
        str: The summarized text.
    """
    if not isinstance(text, str) or not text.strip():
        return ""

    parser = PlaintextParser.from_string(text, Tokenizer(language))

    actual_num_sentences = len(parser.document.sentences)
    total_words_in_document = len(parser.document.words)

    effective_sentences_count = min(sentences_count, actual_num_sentences)

    if effective_sentences_count > total_words_in_document:
        effective_sentences_count = total_words_in_document

    if effective_sentences_count <= 0:
        return ""

    stemmer = Stemmer(language)
    summarizer = LsaSummarizer(stemmer)
    summarizer.stop_words = get_stop_words(language)

    summary_sentences = summarizer(parser.document, sentences_count=effective_sentences_count)
    return " ".join([str(sentence) for sentence in summary_sentences])

before_sentiment_data['lsa_summary'] = before_sentiment_data['summary'].apply(extract_lsa_summary)

display(before_sentiment_data[['summary', 'lsa_summary']].head())

before_sentiment_data.to_csv("/content/lsa_summary.csv")

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("t5-small")
model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")

device = torch.device("cpu")
model.to(device)
model.eval()

before_sentiment_data['summary'] = before_sentiment_data['summary'].fillna('').astype(str)

texts = ["summarize: " + t for t in before_sentiment_data['summary'].tolist()]

batch_size = 64

results = []

total_iters = (len(texts) + batch_size - 1) // batch_size

with torch.no_grad():
    for i in range(0, len(texts), batch_size):

        iteration = (i // batch_size) + 1
        batch_texts = texts[i:i + batch_size]

        inputs = tokenizer(
            batch_texts,
            return_tensors='pt',
            max_length=128,   # 🔥 HUGE speed gain
            truncation=True,
            padding=True
        )

        summary_ids = model.generate(
            inputs['input_ids'],
            max_length=20,    # 🔥 very short summaries
            min_length=5,
            num_beams=1,      # fastest
            do_sample=False
        )

        summaries = tokenizer.batch_decode(summary_ids, skip_special_tokens=True)
        results.extend(summaries)

before_sentiment_data['abstractive_summary'] = results

before_sentiment_data.to_csv("/content/abstractive_summary.csv")

before_sentiment_data