# -*- coding: utf-8 -*-
"""Infosys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gz765Qmt4QFfUcN9oLffZiHaHa6x0GAw

#Loading Dataset
"""

import os
from sklearn.datasets import fetch_20newsgroups

# Fetch the 20 Newsgroups dataset, removing headers, footers, and quotes
# subset='all' includes both 'train' and 'test' sets for completeness
newsgroups_data = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))

print(f"Fetched {len(newsgroups_data.data)} documents.")
print(f"Fetched {len(newsgroups_data.filenames)} filenames.")
# The dataset object 'newsgroups_data' contains 'data' (the text), 'target' (the category labels), and 'filenames' (the original file paths)

"""#Cleaning data"""

import re
from spacy.lang.en import English
from spacy.lang.en.stop_words import STOP_WORDS
from string import punctuation
import nltk
from nltk.stem import WordNetLemmatizer
import spacy


# Download the necessary corpus data (run once)
nltk.download('wordnet')
nltk.download('punkt')

nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])
lemmatizer = WordNetLemmatizer()

def clean_text(text):

    # Remove line breaks and lowercase
    text = re.sub(r'\n', ' ', text)
    text = text.lower()

    # Expand common contractions
    contractions = {
        "don't": "do not",
        "didn't": "did not",
        "doesn't": "does not",
        "can't": "can not",
        "won't": "will not",
        "it's": "it is",
        "i'm": "i am",
        "they're": "they are",
        "we're": "we are",
        "isn't": "is not",
        "aren't": "are not",
        "wasn't": "was not",
        "weren't": "were not",
        "hasn't": "has not",
        "haven't": "have not",
        "hadn't": "had not"
    }

    for c, expanded in contractions.items():
        text = text.replace(c, expanded)

    # Handling numerical values
    text = re.sub(r'\b(19|20)\d{2}\b', ' year ', text)
    text = re.sub(r'\b\d+(\.\d+)?%\b', ' percent ', text)
    text = re.sub(r'\$\d+(\.\d+)?', ' money ', text)
    text = re.sub(r'\b\d+\b', '', text)

    # Remove punctuation
    text = re.sub(r'[^\w\s]', ' ', text)

    # Tokenize
    txt = text.split()

    # Remove stopwords
    txt = [w for w in txt if w not in STOP_WORDS]

    # Remove tokens containing digits
    txt = [w for w in txt if not any(char.isdigit() for char in w)]

    # Remove short tokens
    txt = [w for w in txt if len(w) > 2]

    # Lemmatization
    txt = [lemmatizer.lemmatize(w) for w in txt]

    text = ' '.join(txt)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

def clean_for_summary(text):
    import re

    # Keep sentence structure!
    text = re.sub(r'\n+', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

"""#Dataset"""

import pandas as pd
import numpy as np

dct = {"text":[], "file name":[], "summary":[]}

'''
# dct = {"text":[]}
# for text in files:
#     if text == 'list.csv':
#         continue
#     data = ""
#     with open(path + '/' + text, 'r', encoding='latin-1') as f:
#         data = f.read()
#     data = clean_text(data)
#     dct["text"].append(data)
# dct
'''

for text_document, filename_path in zip(newsgroups_data.data, newsgroups_data.filenames):
    cleaned_data = clean_text(text_document)
    dct["text"].append(cleaned_data)
    # Extract just the filename from the full path
    dct["file name"].append(os.path.basename(filename_path))
    dct["summary"].append(clean_for_summary(text_document))

dataset = pd.DataFrame(dct)
display(dataset.head())
print(dataset['text'][0])
print(dataset.shape)

# Map target indices to actual category names
category_names = [newsgroups_data.target_names[i] for i in newsgroups_data.target]

# Add the category names as a new column to the dataset
dataset['category_name'] = category_names

dataset.drop(columns=['file name'], inplace=True)

dataset.head()

dataset['category_name'] = dataset['category_name'].apply(lambda x: re.sub(r'\.', ', ', x))
dataset

"""#LDA

##CountVectorizer
"""

from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(
    stop_words='english',
    min_df=5,
    max_df=0.7, # Adjusted max_df to be less restrictive
    token_pattern=r'\b[a-zA-Z]{3,}\b'
)

X_counts = count_vectorizer.fit_transform(dataset['text'])
print(f"Shape of X_counts: {X_counts.shape}")

"""##LDA"""

from sklearn.decomposition import LatentDirichletAllocation

lda = LatentDirichletAllocation(
    n_components=30,
    random_state=42
)

# Fit the LDA model to the CountVectorizer output
lda.fit(X_counts)
print("LDA model fitted successfully.")

words = count_vectorizer.get_feature_names_out()

for topic_idx, topic in enumerate(lda.components_):
    print(f"Topic {topic_idx}")
    print([words[i] for i in topic.argsort()[:-10:-1]])

"""#NMF

##TF-IDF Vectorizer
"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(
    stop_words="english",
    max_df=0.9,
    min_df=2
)

X_tfidf = tfidf_vectorizer.fit_transform(dataset["text"])

"""##NMF"""

from sklearn.decomposition import NMF

nmf = NMF(
    n_components=30,
    random_state=42,
    max_iter=500 # Increased max_iter to attempt better convergence
)

nmf.fit(X_tfidf)

words = tfidf_vectorizer.get_feature_names_out()

for topic_idx, topic in enumerate(nmf.components_):
    print(f"Topic {topic_idx}")
    print([words[i] for i in topic.argsort()[:-10:-1]])

"""#Adding topics to dataset"""

lda_output = lda.transform(X_counts)
lda_topic_names = [f"lda_topic_{i}" for i in range(lda.n_components)]
lda_df = pd.DataFrame(lda_output, columns=lda_topic_names)

nmf_output = nmf.transform(X_tfidf)
nmf_topic_names = [f"nmf_topic_{i}" for i in range(nmf.n_components)]
nmf_df = pd.DataFrame(nmf_output, columns=nmf_topic_names)

dataset = pd.concat([dataset, lda_df, nmf_df], axis=1)

print("LDA and NMF topics successfully added to the dataset.")
dataset.head()

dataset['lda_categorical_topic'] = lda_df.idxmax(axis=1).apply(lambda x: int(x.split('_')[-1]))
dataset['nmf_categorical_topic'] = nmf_df.idxmax(axis=1).apply(lambda x: int(x.split('_')[-1]))

for i in range(30):
    dataset = dataset.drop("lda_topic_"+str(i), axis=1)
    dataset = dataset.drop("nmf_topic_"+str(i), axis=1)

print("Categorical LDA and NMF topics added to the dataset.")
dataset.head()

lda_topic_names_map = {}
words = count_vectorizer.get_feature_names_out()

for topic_idx, topic in enumerate(lda.components_):
    top_words_indices = topic.argsort()[:-6:-1] # Get indices of top 5 words
    top_words = [words[i] for i in top_words_indices]
    topic_description = ', '.join(top_words)
    lda_topic_names_map[topic_idx] = f"{topic_description}"

print("Dynamically generated LDA topic names map:")
print(lda_topic_names_map)

dataset['lda_topic_name'] = dataset['lda_categorical_topic'].map(lda_topic_names_map)

print("LDA topic names successfully added to the dataset.")
dataset.head()

nmf_topic_names_map = {}
words_nmf = tfidf_vectorizer.get_feature_names_out()

for topic_idx, topic in enumerate(nmf.components_):
    top_words_indices = topic.argsort()[:-6:-1] # Get indices of top 5 words
    top_words = [words_nmf[i] for i in top_words_indices]
    topic_description = ', '.join(top_words)
    nmf_topic_names_map[topic_idx] = f"{topic_description}"

print("Dynamically generated NMF topic names map:")
print(nmf_topic_names_map)

dataset['nmf_topic_name'] = dataset['nmf_categorical_topic'].map(nmf_topic_names_map)

# The following line is commented out to retain 'lda_categorical_topic' and 'nmf_categorical_topic'
# dataset.drop(columns=['lda_categorical_topic', 'nmf_categorical_topic'], inplace=True)

print("NMF topic names successfully added to the dataset.")
dataset.head()

"""#Copy"""

df = dataset.copy()

df.head()

"""#Evaluating LDA & NMF to choose one"""

# # Evaluate LDA
# print("--- LDA Evaluation ---")
# lda_cross_tab = pd.crosstab(df['category_name'], df['lda_topic_name'])
# print("Cross-tabulation of true categories vs. LDA topic names:")
# display(lda_cross_tab)

# # Identify dominant category for each LDA topic
# print("\nDominant true category for each LDA topic:")
# for topic_name in lda_cross_tab.columns:
#     dominant_category = lda_cross_tab[topic_name].idxmax()
#     count = lda_cross_tab[topic_name].max()
#     total_in_topic = lda_cross_tab[topic_name].sum()
#     if total_in_topic > 0:
#         percentage = (count / total_in_topic) * 100
#     else:
#         print(f"LDA Topic: '{topic_name}' -> No documents assigned.")

# # Identify dominant LDA topic for each true category
# print("\nDominant LDA topic for each true category:")
# for category_name in lda_cross_tab.index:
#     dominant_topic = lda_cross_tab.loc[category_name].idxmax()
#     count = lda_cross_tab.loc[category_name].max()
#     total_in_category = lda_cross_tab.loc[category_name].sum()
#     if total_in_category > 0:
#         percentage = (count / total_in_category) * 100
#     else:
#         print(f"Category: '{category_name}' -> No LDA topic assigned.")


# # Evaluate NMF
# print("\n--- NMF Evaluation ---")
# nmf_cross_tab = pd.crosstab(df['category_name'], df['nmf_topic_name'])
# print("Cross-tabulation of true categories vs. NMF topic names:")
# display(nmf_cross_tab)

# # Identify dominant category for each NMF topic
# print("\nDominant true category for each NMF topic:")
# for topic_name in nmf_cross_tab.columns:
#     dominant_category = nmf_cross_tab[topic_name].idxmax()
#     count = nmf_cross_tab[topic_name].max()
#     total_in_topic = nmf_cross_tab[topic_name].sum()
#     if total_in_topic > 0:
#         percentage = (count / total_in_topic) * 100
#     else:
#         print(f"NMF Topic: '{topic_name}' -> No documents assigned.")

# # Identify dominant NMF topic for each true category
# print("\nDominant NMF topic for each true category:")
# for category_name in nmf_cross_tab.index:
#     dominant_topic = nmf_cross_tab.loc[category_name].idxmax()
#     count = nmf_cross_tab.loc[category_name].max()
#     total_in_category = nmf_cross_tab.loc[category_name].sum()
#     if total_in_category > 0:
#         percentage = (count / total_in_category) * 100
#     else:
#         print(f"Category: '{category_name}' -> No NMF topic assigned.")

# import matplotlib.pyplot as plt
# import seaborn as sns

# # Plotting LDA Cross-tabulation
# plt.figure(figsize=(16, 10))
# sns.heatmap(lda_cross_tab, cmap='YlGnBu', annot=False, fmt='d', linewidths=.5, linecolor='gray')
# plt.title('LDA: True Categories vs. LDA Topic Names', fontsize=16)
# plt.xlabel('LDA Topic Names', fontsize=12)
# plt.ylabel('True Category Names', fontsize=12)
# plt.xticks(rotation=90, ha='right', fontsize=8)
# plt.yticks(rotation=0, fontsize=8)
# plt.tight_layout()
# plt.show()

# import matplotlib.pyplot as plt
# import seaborn as sns

# # Plotting NMF Cross-tabulation
# plt.figure(figsize=(16, 10))
# sns.heatmap(nmf_cross_tab, cmap='YlGnBu', annot=False, fmt='d', linewidths=.5, linecolor='gray')
# plt.title('NMF: True Categories vs. NMF Topic Names', fontsize=16)
# plt.xlabel('NMF Topic Names', fontsize=12)
# plt.ylabel('True Category Names', fontsize=12)
# plt.xticks(rotation=90, ha='right', fontsize=8)
# plt.yticks(rotation=0, fontsize=8)
# plt.tight_layout()
# plt.show()

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score

# Encode true category names to numerical labels
label_encoder = LabelEncoder()
true_labels = label_encoder.fit_transform(df['category_name'])

# Recreate 'nmf_categorical_topic' in df, as it was previously dropped
df['nmf_categorical_topic'] = nmf_df.idxmax(axis=1).apply(lambda x: int(x.split('_')[-1]))

# Get topic assignments for LDA and NMF
lda_topic_assignments = df['lda_categorical_topic']
nmf_topic_assignments = df['nmf_categorical_topic']

# Calculate Adjusted Rand Index (ARI)
lda_ari = adjusted_rand_score(true_labels, lda_topic_assignments)
nmf_ari = adjusted_rand_score(true_labels, nmf_topic_assignments)

# Calculate Normalized Mutual Information (NMI)
lda_nmi = normalized_mutual_info_score(true_labels, lda_topic_assignments)
nmf_nmi = normalized_mutual_info_score(true_labels, nmf_topic_assignments)

print("\n--- Topic Model Performance Metrics ---")
print(f"Adjusted Rand Index (ARI):")
print(f"  LDA: {lda_ari:.4f}")
print(f"  NMF: {nmf_ari:.4f}")

print(f"\nNormalized Mutual Information (NMI):")
print(f"  LDA: {lda_nmi:.4f}")
print(f"  NMF: {nmf_nmi:.4f}")

print("\nHigher values for both ARI and NMI indicate better agreement with the true categories.")

dataset.drop(columns=['nmf_topic_name'], inplace=True)
dataset.drop(columns=['nmf_categorical_topic'], inplace=True)
display(dataset.head())

"""#Copy"""

df = dataset.copy()

df.head()

"""#Sentiment analysis"""

import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import matplotlib.pyplot as plt
import seaborn as sns

# Download the VADER lexicon if not already downloaded
try:
    nltk.data.find('sentiment/vader_lexicon.zip')
except LookupError:
    nltk.download('vader_lexicon')

sia = SentimentIntensityAnalyzer()

def get_sentiment_scores(text):
    return sia.polarity_scores(text)

def categorize_sentiment(score):
    if score >= 0.05:
        return 'Positive'
    elif score <= -0.05:
        return 'Negative'
    else:
        return 'Neutral'

dataset['sentiment_scores'] = dataset['text'].apply(get_sentiment_scores)
dataset['compound_sentiment'] = dataset['sentiment_scores'].apply(lambda x: x['compound'])
dataset['sentiment_category'] = dataset['compound_sentiment'].apply(categorize_sentiment)

dataset

# Method 1: Aggregate sentiment per topic
print("\n--- Method 1: Aggregate Sentiment per LDA Topic ---")
aggregated_sentiment_lda = dataset.groupby('lda_topic_name')['compound_sentiment'].mean().sort_values(ascending=False)
print("Average Compound Sentiment per LDA Topic:")
print(aggregated_sentiment_lda)

# Method 2: Sentiment distribution per topic
print("\n--- Method 2: Sentiment Distribution per LDA Topic ---")
sentiment_distribution_lda = pd.crosstab(dataset['lda_topic_name'], dataset['sentiment_category'])
print("Sentiment Category Distribution per LDA Topic:")
print(sentiment_distribution_lda)

# Visualize sentiment distribution per LDA topic
plt.figure(figsize=(15, 8))
sentiment_distribution_lda.plot(kind='bar', stacked=True, colormap='viridis', figsize=(15, 8))
plt.title('Sentiment Distribution per LDA Topic', fontsize=16)
plt.xlabel('LDA Topic Name', fontsize=12)
plt.ylabel('Number of Documents', fontsize=12)
plt.xticks(rotation=90, ha='right', fontsize=10)
plt.yticks(fontsize=10)
plt.legend(title='Sentiment Category', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

print("\n--- Method 3 (Bonus): Weighted by Topic Probability ---")

# 'lda_output' already contains the soft assignments (document-topic probabilities)
doc_topic_probs = lda_output

# Ensure compound_sentiment is a numpy array for matrix multiplication
compound_sentiment_array = dataset['compound_sentiment'].values

# Calculate weighted topic sentiment
topic_sentiment_weighted = (doc_topic_probs.T @ compound_sentiment_array) / doc_topic_probs.sum(axis=0)

# Create a Series for better readability, mapping to topic names
weighted_topic_sentiment_series = pd.Series(topic_sentiment_weighted, index=list(lda_topic_names_map.values()))

print("Weighted Average Compound Sentiment per LDA Topic (using soft assignments):")
print(weighted_topic_sentiment_series.sort_values(ascending=False))

"""#Saving models"""

import joblib
import pickle
import os

# Define a directory to save the assets
output_dir = 'model_assets'
os.makedirs(output_dir, exist_ok=True)

print(f"\nSaving assets to: {output_dir}/")

# 1. Save the clean_text function
with open(os.path.join(output_dir, 'clean_text_function.pkl'), 'wb') as f:
    pickle.dump(clean_text, f)
print("Saved clean_text_function.pkl")

# 2. Save the CountVectorizer
joblib.dump(count_vectorizer, os.path.join(output_dir, 'count_vectorizer.joblib'))
print("Saved count_vectorizer.joblib")

# 3. Save the LDA model
joblib.dump(lda, os.path.join(output_dir, 'lda_model.joblib'))
print("Saved lda_model.joblib")

# 4. Save the TfidfVectorizer
joblib.dump(tfidf_vectorizer, os.path.join(output_dir, 'tfidf_vectorizer.joblib'))
print("Saved tfidf_vectorizer.joblib")

# 5. Save the NMF model
joblib.dump(nmf, os.path.join(output_dir, 'nmf_model.joblib'))
print("Saved nmf_model.joblib")

# 6. Save the SentimentIntensityAnalyzer
with open(os.path.join(output_dir, 'sentiment_analyzer.pkl'), 'wb') as f:
    pickle.dump(sia, f)
print("Saved sentiment_analyzer.pkl")

# 7. Save LDA topic names map
with open(os.path.join(output_dir, 'lda_topic_names_map.pkl'), 'wb') as f:
    pickle.dump(lda_topic_names_map, f)
print("Saved lda_topic_names_map.pkl")

# 8. Save NMF topic names map
with open(os.path.join(output_dir, 'nmf_topic_names_map.pkl'), 'wb') as f:
    pickle.dump(nmf_topic_names_map, f)
print("Saved nmf_topic_names_map.pkl")

# 9. Save LabelEncoder
joblib.dump(label_encoder, os.path.join(output_dir, 'label_encoder.joblib'))
print("Saved label_encoder.joblib")

print("\nAll specified assets have been saved.")

# Example of how to load them back:
# loaded_clean_text = joblib.load(os.path.join(output_dir, 'clean_text_function.pkl'))
# loaded_count_vectorizer = joblib.load(os.path.join(output_dir, 'count_vectorizer.joblib'))

simplified_lda_topic_names_map = {
    0: 'Software',
    1: 'Bikes',
    2: 'Space',
    3: 'Power',
    4: 'Encryption',
    5: 'Hockey',
    6: 'Politics',
    7: 'Government',
    8: 'Money',
    9: 'Religion',
    10: 'Computers',
    11: 'Guns',
    12: 'General',
    13: 'Sales',
    14: 'Disk Drive',
    15: 'Files',
    16: 'Conversation',
    17: 'Medical',
    18: 'Technology',
    19: 'Mideast',
    20: 'Sports',
    21: 'Christianity',
    22: 'Automotive',
    23: 'Gaming',
    24: 'Queries',
    25: 'Cars',
    26: 'Law',
    27: 'Armenian Conflict',
    28: 'Internet',
    29: 'Windows'
}

print("Simplified LDA topic names map created.")

# Create a new DataFrame copy to avoid modifying the existing 'df'
df_with_both_topic_names = df.copy()

# Add a new column for the simplified LDA topic names
df_with_both_topic_names['lda_simplified_topic_name'] = df_with_both_topic_names['lda_categorical_topic'].map(simplified_lda_topic_names_map)

# # Add a new column for the verbose (original detailed) LDA topic names
# df_with_both_topic_names['lda_verbose_topic_name'] = df_with_both_topic_names['lda_categorical_topic'].map(lda_topic_names_map)

# Optionally, remove the original 'lda_topic_name' if it was present and not needed
# if 'lda_topic_name' in df_with_both_topic_names.columns:
#     df_with_both_topic_names.drop(columns=['lda_topic_name'], inplace=True)

print("New DataFrame 'df_with_both_topic_names' created with both simplified and verbose LDA topic names.")
df_with_both_topic_names

df

dataset

import os

output_dir = 'processed_data'
os.makedirs(output_dir, exist_ok=True)

# Save the final processed dataset (after sentiment analysis) to a CSV file
dataset.to_csv(os.path.join(output_dir, 'processed_newsgroups_dataset_after_sentiment.csv'), index=False)
print(f"Processed dataset (after sentiment analysis) saved to {os.path.join(output_dir, 'processed_newsgroups_dataset_after_sentiment.csv')}")

# Save the dataset before sentiment analysis
df.to_csv(os.path.join(output_dir, 'processed_newsgroups_dataset_before_sentiment.csv'), index=False)
print(f"Processed dataset (before sentiment analysis) saved to {os.path.join(output_dir, 'processed_newsgroups_dataset_before_sentiment.csv')}")

# Save dataset with Topic Names
df_with_both_topic_names.to_csv(os.path.join(output_dir, 'processed_newsgroups_dataset_with_topic_names.csv'), index=False)
print(f"Processed dataset (with Topic Names) saved to {os.path.join(output_dir, 'processed_newsgroups_dataset_with_topic_names.csv')}")